// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvFtrfvb5jjFOZmGjcdIIfIO7k1BDU69M',
    appId: '1:123505586066:web:5c48a5becd811969d11b4b',
    messagingSenderId: '123505586066',
    projectId: 'qlnv-12713',
    authDomain: 'qlnv-12713.firebaseapp.com',
    storageBucket: 'qlnv-12713.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB684-Gfvq0bfMqbWVfKXsQBQWj8id5dcs',
    appId: '1:123505586066:android:0f08fc11db45625cd11b4b',
    messagingSenderId: '123505586066',
    projectId: 'qlnv-12713',
    storageBucket: 'qlnv-12713.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlo9-h-seL67A7szIFr8dW-EPaTnT8nn4',
    appId: '1:123505586066:ios:77952c950d66e3d8d11b4b',
    messagingSenderId: '123505586066',
    projectId: 'qlnv-12713',
    storageBucket: 'qlnv-12713.appspot.com',
    iosBundleId: 'com.example.quanlynv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlo9-h-seL67A7szIFr8dW-EPaTnT8nn4',
    appId: '1:123505586066:ios:abf24f0f9c79a308d11b4b',
    messagingSenderId: '123505586066',
    projectId: 'qlnv-12713',
    storageBucket: 'qlnv-12713.appspot.com',
    iosBundleId: 'com.example.quanlynv.RunnerTests',
  );
}
